### ISSUE TITLE
the timestamp adds over shorts

### ISSUE THREAD

**Issue by lephiz69** [ynshung/better-yt-shorts#149]
idk what to call that but heres  a [screenshot](https://prnt.sc/aX3vPZSO-uCb)

**Comment by adsuth** [comment]
Something really weird going on with the duration prop on the video element.

It seems like it accumulates with shorts as more shorts are generated, and so does the current time

**Comment by SamiSul** [comment]
I will look into this today and hopefully find out the reason

**Comment by samisul** [comment]
@adsuth couldn't even replicate locally, according to a comment on [issue 145](https://github.com/ynshung/better-yt-shorts/issues/145) the problem there is fixed, could it be that this one is also fixed?

**Comment by lephiz69** [comment]
> @adsuth couldn't even replicate locally, according to a comment on [issue 145](https://github.com/ynshung/better-yt-shorts/issues/145) the problem there is fixed, could it be that this one is also fixed?


https://github.com/ynshung/better-yt-shorts/assets/147328269/ca88c8cf-2bc1-4315-ad55-ee16d50d7047
Here's a video

**Comment by ynshung** [comment]
@lephiz69 Which version of the extension are you using? We also need info of your Google Chrome version (`chrome://version/`) and your operating system

**Comment by adsuth** [comment]
> @adsuth couldn't even replicate locally, according to a comment on [issue 145](https://github.com/ynshung/better-yt-shorts/issues/145) the problem there is fixed, could it be that this one is also fixed?

This is definitely an issue on Chrome. Seems to be fine on Firefox though...

**Comment by lephiz69** [comment]
> @lephiz69 Which version of the extension are you using? We also need info of your Google Chrome version (`chrome://version/`) and your operating system

Earlier I was using 3.0.1 (the above video was recorded in 3.0.1)

I updated and the issue still persists.
and 118.0.2088.57 (Official build) (64-bit) (Microsoft Edge)

Here's a video from 3.1.0

https://github.com/ynshung/better-yt-shorts/assets/147328269/2da0e8ad-85b4-4515-9af0-b58a7353c827

**Comment by lephiz69** [comment]
It works on google chrome! and there is no screen upwards thing while using the scroll wheel (Ex. 0:03 in the above video)

Here's a video of that as well.
https://github.com/ynshung/better-yt-shorts/assets/147328269/0f119d18-8b7f-49cf-b7ad-06627482bd3d

**Comment by lephiz69** [comment]
**UPDATE**:
I've noticed that this issue ONLY works on my account! (for some weird reason)

https://github.com/ynshung/better-yt-shorts/assets/147328269/84a27637-b2ac-4123-8334-b785fa771c89
I will be out of town for tomorrow's entirety so I cannot update this case in the following day.

**Comment by samisul** [comment]
thats very odd :/ I'll try to look into why that could be the case. maybe browser caching issue? cant see how that could be the case though

**Comment by adsuth** [comment]
> thats very odd :/ I'll try to look into why that could be the case. maybe browser caching issue? cant see how that could be the case though

When I was testing for #162 just now, I logged out of yt for the screen recording. Logging back in, its stopped working - both this issue and the binds.

Very, very weird

**Comment by samisul** [comment]
will look into this after work and update you if i find anything. very weird

**Comment by adsuth** [comment]
Another update to this issue, #140 also doesnt work on my main account, but does on a side account.

the selector `#factoids ytd-factoid-renderer:nth-child(3)` specifically finds nothing on the main account, but finds the element on the other one.

Its like the site is out of date for specific accounts which makes absolutely zero sense to me unless youtube specifically caches things on the server per account?

**Comment by lephiz69** [comment]
I just misspelled "discrepancy" four times 💀 

I've updated the title, still out of town so cannot test rn

**Comment by tiagohconte** [comment]
The site can be different for each user/system/browser. They usually do that to perform usability tests.

We could place fallback in some selectors (like #140) so more versions are covered.

**Comment by lephiz69** [comment]
Oh yeah speaking of that, I've recently gotten a UI update which doesn't affect shorts (I think) now, when I hold the space bar or a click in a video (not a short) it 2x speeds the video
BUT I think I have had this issue before the new UI

**Comment by adsuth** [comment]
> Oh yeah speaking of that, I've recently gotten a UI update which doesn't affect shorts (I think) now, when I hold the space bar or a click in a video (not a short) it 2x speeds the video
> BUT I think I have had this issue before the new UI

Yeah thats specifically a youtube change, got that as well

**Comment by lephiz69** [comment]
another update:
it works when using a different browser but same account. I think it is something wrong with the browser, but it works fine in other accounts!! wtf is the problem!?

**Comment by lephiz69** [comment]
THIS ISSUE HAS BEEN FIXED! just, randomly.

**Comment by adsuth** [comment]
Dont think this is an issue anymore, should this be closed @ynshung ?
